const intro=document.getElementById('intro'), page=document.querySelector('.page-shell');
const cursor=document.getElementById('cursor'), menuButton=document.getElementById('menuButton'), navLinks=document.getElementById('navLinks');
window.addEventListener('load',()=>setTimeout(()=>{intro.style.transition='opacity .55s ease,visibility .55s ease';intro.style.opacity='0';intro.style.visibility='hidden';page.style.transition='opacity .5s ease';page.style.opacity='1'},1800));
menuButton.addEventListener('click',()=>navLinks.classList.toggle('open'));
document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('big'));el.addEventListener('mouseleave',()=>cursor.classList.remove('big'))});
window.addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});
document.querySelectorAll('.skill-head').forEach(b=>b.addEventListener('click',()=>{const p=b.closest('.skill-group');document.querySelectorAll('.skill-group').forEach(g=>{if(g!==p)g.classList.remove('open')});p.classList.toggle('open')}));
document.querySelectorAll('.journey-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.journey-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.timeline').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.target).classList.add('active')}));
const serviceData={backend:{title:'Backend Developer',items:['Provide Rest API.','Make sure the service is running well.','Processing large data.','Query optimization.','Payment Method/Gateway.','Bulk Upload Topup.']},frontend:{title:'Frontend Developer',items:['Develop the user interface.','Web page development.','Integrate with back end services.','Develop Responsive UI.']}};
const modal=document.getElementById('serviceModal'),modalTitle=document.getElementById('modalTitle'),modalList=document.getElementById('modalList');
document.querySelectorAll('.more-button').forEach(btn=>btn.addEventListener('click',()=>{const d=serviceData[btn.dataset.service];modalTitle.textContent=d.title;modalList.innerHTML=d.items.map(x=>`<li>✓ ${x}</li>`).join('');modal.classList.add('show')}));
document.getElementById('closeModal').addEventListener('click',()=>modal.classList.remove('show'));
modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});
document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();const n=document.getElementById('name').value.trim(),em=document.getElementById('email').value.trim(),p=document.getElementById('project').value.trim(),m=document.getElementById('message').value.trim();window.location.href=`mailto:naufal.dawam.dz@gmail.com?subject=${encodeURIComponent('[Portfolio] '+p)}&body=${encodeURIComponent(`Name: ${n}\nEmail: ${em}\nProject: ${p}\n\n${m}`)}`;showToast('Opening your email client…')});
function showToast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
const nav=document.querySelectorAll('#navLinks a');const obs=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting)nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${en.target.id}`))}),{rootMargin:'-35% 0px -55% 0px'});document.querySelectorAll('main section[id]').forEach(s=>obs.observe(s));